# git clone <url>                       copying a repository (only 1 per repo)
# git status                            (files you made changes = red) (green = commited files)
# git add .                             (. does all changes, <filename> for single file)
# git commit -m "Some message Here"     (prep to push)
# git push origin master                (push file out)
# git pull                              (update all repo)
